version: "3.8"

services:
  regional-fase2-si-backend:
    image: bilinguismotalentum/regional-fase2-si-backend:1.2.4
    container_name: regional-fase2-si-backend
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      NODE_ENV : production
      APP_PORT: 4000
      SUPPORT_EMAIL : regional.notificacion@outlook.com
      URL_SWAGGER_PRODUCTION : http://localhost:4002/api/v1
      WEB_SUPPORT :
      HAS_SYNCHRONIZATION: true
      IS_TUMLAB: true
      CORS_WHITELIST: "http://localhost:8084,http://tumlab.local:3002,http://localhost:3000,http://localhost:4002,http://localhost:4000,http://localhost:3003,http://localhost:3005"
      FRONTEND_URL : "http://tumlab.local:3002"
      DEFAULT_PASSWORD_ENABLED: "true"
      DEFAULT_PASSWORD_VALUE: "12345Az!"
      EMAIL_SMTP_DOMAIN: "smtp-mail.outlook.com"
      EMAIL_SMTP_PASSWORD : "no_aplica"
      EMAIL_SMTP_PORT : 587
      EMAIL_SMTP_SECURE : false
      EMAIL_SMTP_USER : "no_aplica"
      KEYCLOAK_DB_PORT : 5432
      KEYCLOAK_DB_ADDR : host.docker.internal
      KEYCLOAK_DB_DATABASE : authentication
      KEYCLOAK_DB_USER : root
      KEYCLOAK_DB_PASSWORD : "root"
      KEYCLOAK_AUTH_SERVER_URL : http://host.docker.internal:8080/auth
      KEYCLOAK_CLIENT_ID : regional-client
      KEYCLOAK_ID : regional-client
      KEYCLOAK_USER : admin
      KEYCLOAK_PASSWORD : admin
      KEYCLOAK_REALM : regional-realm
      KEYCLOAK_SECRET : B8yPzlT4txHjz1YKCgAVQNV7E0CrZoFd
      MINIO_ACCESSKEY : admin
      MINIO_HOST : localhost
      MINIO_NAME : regional
      MINIO_PORT : 443
      MINIO_SECRETKEY : admin
      MINIO_SSL : true
      MYSQL_DATABASE : regional
      MYSQL_HOST : host.docker.internal
      MYSQL_PASSWORD : "12345Az!"
      MYSQL_PORT : 3306
      MYSQL_ROOT_PASSWORD : "rootpassword"
      MYSQL_USER : master
      QUEUE_HOST: 192.168.20.20:5672
      QUEUE_USERNAME: synchronizer-agent
      QUEUE_PASSWORD: 12345Az!
      QUEUE_VHOST: /
      QUEUE_NAME: regional_synchronizer
    ports:
      - 4002:4000
    #volumes:
    #  - /tumlab/syncthing/tumlab.config:/app/public/tumlab.config
    networks:
      - regional-net

  regional-fase2-si-backend-bulk:
    image: bilinguismotalentum/regional-fase2-si-backend-bulk:1.0.3
    container_name: regional-fase2-si-backend-bulk
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      NODE_ENV : prod
      PORT : 3001
      URL_SWAGGER_PRODUCTION : http://localhost:4003
      HAS_SYNCHRONIZATION: true
      IS_TUMLAB: true
      FRONTEND_URL : "http://tumlab.local:3002"
      SUPPORT_EMAIL: "no_aplica"
      DEFAULT_PASSWORD_ENABLED: "true"
      DEFAULT_PASSWORD_VALUE: "12345Az!"
      DB_DATABASE : regional
      DB_HOST : host.docker.internal
      DB_PASSWORD : "12345Az!"
      DB_PORT : 3306
      DB_USER : master
      KEYCLOAK_AUTH_SERVER_URL : http://host.docker.internal:8080/auth
      KEYCLOAK_CLIENT_ID : regional-client
      KEYCLOAK_ID : regional-client
      KEYCLOAK_USER : admin
      KEYCLOAK_PASSWORD : admin
      KEYCLOAK_REALM : regional-realm
      KEYCLOAK_SECRET : B8yPzlT4txHjz1YKCgAVQNV7E0CrZoFd
      EMAIL_HOST: "smtp-mail.outlook.com"
      EMAIL_PORT: "587"
      EMAIL_SECURE: "false"
      EMAIL_USER: "no_aplica"
      EMAIL_PASSWORD: "no_aplica"
      EMAIL_FROM: "no_aplica"
      QUEUE_HOST: 192.168.20.20:5672
      QUEUE_USERNAME: synchronizer-agent
      QUEUE_PASSWORD: 12345Az!
      QUEUE_VHOST: /
      QUEUE_NAME: regional_synchronizer
    ports:
      - 4003:3001
    networks:
      - regional-net

  regional-fase2-si-synchronization-agent:
    image: bilinguismotalentum/regional-fase2-si-synchronization-agent:1.0.0
    container_name: regional-fase2-si-synchronization-agent
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      NODE_ENV : prod
      APP_PORT : 3002
      API_KEY: "7kiNYGNEa6njqYUU9E1FEhYibT6iyeCyakvrWiVxy6gmWAe0pbkNSMQ19htdo2Y1"
      LOCAL_QUEUE_HOST: 192.168.20.20:5672
      LOCAL_QUEUE_USERNAME: synchronizer-agent
      LOCAL_QUEUE_PASSWORD: 12345Az!
      LOCAL_QUEUE_VHOST: /
      LOCAL_QUEUE_NAME: "regional_synchronizer"
      REMOTE_QUEUE_HOST: "mq.talentum.edu.co"
      REMOTE_QUEUE_USERNAME: "guest"
      REMOTE_QUEUE_PASSWORD: "Nh3r!yj6UatpxK*Vsb4"
      REMOTE_QUEUE_VHOST: /
      REMOTE_QUEUE_NAME: "regional_synchronizer"
      DB_DATABASE : regional
      DB_HOST : host.docker.internal
      DB_PASSWORD : "12345Az!"
      DB_PORT : 3306
      DB_USER : master
    ports:
      - 4006:3002
    networks:
      - regional-net

  regional-frontend:
    image: bilinguismotalentum/regional-fase2-si-frontend:1.5.6
    container_name: regional-2-si-frontend
    networks:
      - regional-net
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4002/api/v1
      NEXT_PUBLIC_DOWNLOAD_VIDEO_GAME_ANDROID: https://storage.googleapis.com/regional-2/apk/MundoInteractivoVirtual3D.apk
      NEXT_PUBLIC_DOWNLOAD_VIDEO_GAME_WINDOWS: https://drive.google.com/file/d/1NR6UZ5m8_tXgvLnrRU_5TVYcbUJtrl9-/view?usp=sharing
      NEXT_PUBLIC_GAME_URL: http://localhost:8084
      NEXT_PUBLIC_PASSWORD_IMAGE: Ww0KICB7DQogICAgImltYWdlIjogInRyaWFuZ2xlIiwNCiAgICAicGF0aCI6ICIvaW1hZ2VzL2ljb25zL2ZpZ3VyZV90cmlhbmdsZS5zdmciLA0KICAgICJjb2RlIjogImU0ZGFhZDI5LWRlNjYtNDU5My1iNDljLTE2ODA1NTk4NzgzOSINCiAgfSwNCiAgew0KICAgICJpbWFnZSI6ICJyaG9tYnVzIiwNCiAgICAicGF0aCI6ICIvaW1hZ2VzL2ljb25zL2ZpZ3VyZV9kaWFtb25kLnN2ZyIsDQogICAgImNvZGUiOiAiZDZhZTQ4NTQtNjlmOS00MTE3LTk1YTAtYjIwOTAxNmY0MDllIg0KICB9LA0KICB7DQogICAgImltYWdlIjogInNxdWFyZSIsDQogICAgInBhdGgiOiAiL2ltYWdlcy9pY29ucy9maWd1cmVfc3F1YXJlLnN2ZyIsDQogICAgImNvZGUiOiAiYTY4NDkwYmItNzE4ZS00MDZkLWE1MTQtMGFlNWViMDI5MGZlIg0KICB9LA0KICB7DQogICAgImltYWdlIjogInJob21ib2lkIiwNCiAgICAicGF0aCI6ICIvaW1hZ2VzL2ljb25zL2ZpZ3VyZV9xdWFkcmlsYXRlcmFsLnN2ZyIsDQogICAgImNvZGUiOiAiY2ZkYjdhYzktMTgyMC00MDgzLWEwOGYtZjNkYTEwMGFiODUxIg0KICB9LA0KICB7DQogICAgImltYWdlIjogImludmVydGVkX3RyaWFuZ2xlIiwNCiAgICAicGF0aCI6ICIvaW1hZ2VzL2ljb25zL2ZpZ3VyZV9pbnZlcnRlZF90cmlhbmdsZS5zdmciLA0KICAgICJjb2RlIjogIjJmOGU5YWZlLTg0YjEtNGMyMy1hYjEyLTFjODhjNWQzNmQ0OCINCiAgfSwNCiAgew0KICAgICJpbWFnZSI6ICJjaXJjbGUiLA0KICAgICJwYXRoIjogIi9pbWFnZXMvaWNvbnMvZmlndXJlX2NpcmNsZS5zdmciLA0KICAgICJjb2RlIjogImE0NDhkZGZjLWU5MmMtNDkxZS05OTJiLTkxNmVkNmJiN2Q5YiINCiAgfQ0KXQ==
    ports:
         - "3002:3000"

  regional-mundo3D:
    image: bilinguismotalentum/regional-game:1.1.3
    container_name: regional-game
    ports:
      - "3005:80"
    volumes:
      - ./serverdata.json:/regional/StreamingAssets/serverdata.json
    networks:
      - regional-net
    restart: always

networks:
  regional-net:
    driver: bridge